name: MLB Predictor Automatico

on:
  schedule:
    # Se ejecuta todos los días a las 10:00 AM UTC (Ajusta según tu zona horaria)
    - cron: '0 10 * * *'
  workflow_dispatch: # Te permite activar el modelo manualmente haciendo clic en un botón desde el móvil

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso crucial para que la máquina pueda guardar el reporte en tu GitHub

    steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Descargar Datos MLB API
      run: python mlb_data.py

    - name: Generar Predicciones Machine Learning
      run: python predict.py

    - name: Guardar y Publicar Resultados
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        git add juegos_hoy.csv PREDICCIONES.md || true
        git commit -m "Predicciones del día actualizadas de forma automática" || true
        git push true
